In [2]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

WARNING:tensorflow:From c:\Users\My\Desktop\Study Material\Deep Learning project\venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [3]:
### load the ann model,scaler and onehot
model = load_model('model.h5')
## load the encoder and scaler
with open('onehot_encoder_geo.pkl','rb') as file:
    onehot_encoder_geo=pickle.load(file)

with open('label_encoder_gender.pkl','rb') as file:
    label_encoder_gender=pickle.load(file)

with open('scaler.pkl','rb') as file:
    scaler=pickle.load(file)

WARNING:tensorflow:From c:\Users\My\Desktop\Study Material\Deep Learning project\venv\Lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

In [4]:
input_data={
'CreditScore':600,
'Gender':'Male',                
'Age':40,                  
'Tenure':3,              
'Balance':60000,             
'NumOfProducts':2,          
'HasCrCard':1,             
'IsActiveMember':1,       
'EstimatedSalary':50000,                     
'Geography':'France'    
}

In [11]:
input_df =pd.DataFrame([input_data])

In [8]:
encoded_geo = onehot_encoder_geo.transform([[input_data['Geography']]]).toarray()
encoded_geo_df = pd.DataFrame(encoded_geo,columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
encoded_geo_df

c:\Users\My\Desktop\Study Material\Deep Learning project\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [12]:
input_data=pd.concat([input_df.reset_index(drop=True),encoded_geo_df],axis=1)
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography
0,600,Male,40,3,60000,2,1,1,50000,France

In [13]:
input_df['Gender']=label_encoder_gender.transform(input_df['Gender'])
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography
0,600,1,40,3,60000,2,1,1,50000,France

In [14]:
## concat ONEHOT ENCODED DATA
input_df=pd.concat([input_df.drop("Geography",axis=1),encoded_geo_df],axis=1)
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [16]:
### Scaling the input data]
input_scaled = scaler.transform(input_df)

In [17]:
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [19]:
### Predictr Churn
pred = model.predict(input_scaled)
pred

1/1 [==============================] - 0s 17ms/step

array([[0.02705899]], dtype=float32)

In [22]:
pred_proba = pred[0][0]

In [23]:
pred_proba

0.027058989

In [24]:
if pred_proba > 0.5:
    print("The customer is likely to churn")
else:
    print("The customer is not likely to churn")

The customer is not likely to churn